version: "3.8"

services:
  postgresql-database:
    image: bitnami/postgresql:15
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: layer-arch-payments
  redis:
    image: redislabs/redisearch:latest
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --requirepass "local"
      - --loadmodule /usr/lib/redis/modules/rejson.so
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "local", "ping"]
      interval: 5s
