version: "3.8"

services:
  postgresql-database:
    image: bitnami/postgresql:15
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: layer-arch-payments
